# Generated by Django 3.0.8 on 2020-08-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aproductId', models.CharField(max_length=200)),
                ('athickness', models.CharField(max_length=200)),
                ('awidth', models.CharField(max_length=200)),
                ('alength', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DeckingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dproductId', models.CharField(max_length=200)),
                ('dthickness', models.CharField(max_length=200)),
                ('dwidth', models.CharField(max_length=200)),
                ('dlength', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InquiryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('logs', models.CharField(max_length=200)),
                ('veneers', models.CharField(max_length=200)),
                ('decking', models.CharField(max_length=200)),
                ('boards', models.CharField(max_length=200)),
                ('flooring', models.CharField(max_length=200)),
                ('skirtings', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LumberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lproductId', models.CharField(max_length=200)),
                ('lthickness', models.CharField(max_length=200)),
                ('lwidth', models.CharField(max_length=200)),
                ('llength', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MoldingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mproductId', models.CharField(max_length=200)),
                ('mthickness', models.CharField(max_length=200)),
                ('mwidth', models.CharField(max_length=200)),
                ('mlength', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VeneerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vproductId', models.CharField(max_length=200)),
                ('vthickness', models.CharField(max_length=200)),
                ('vwidth', models.CharField(max_length=200)),
                ('vlength', models.CharField(max_length=200)),
            ],
        ),
    ]
